apiVersion: apps/v1
kind: Deployment

metadata:
  name: microservicio-devops

spec:
  replicas: 2

  selector:
    matchLabels:
      app: microservicio-devops

  template:
    metadata:
      labels:
        app: microservicio-devops

    spec:
      containers:
      - name: microservicio-devops

        image: gmonlep/microservicio-devops:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 3000

        env:
        - name: PORT
          value: "3000"

        - name: MONGO_URI
          value: mongodb://mongodb:27017/mi_base_datos